israeli_car_market_full_compilation = {
    "Toyota": [
        "Yaris",
        "Corolla",
        "Auris",
        "Camry",
        "Prius",
        "C-HR",
        "RAV4",
        "Land Cruiser",
        "Hilux",
        "Sienna",
        "Verso",
        "Aygo",
        "Starlet",
        "Avensis",
        "iQ",
        "Urban Cruiser",
        "Space Verso",
        "Prius+",
        "Proace",
        "bZ4X",
        "Yaris Cross",
        "Highlander",
        "Corolla Cross"
    ],
    "Hyundai": [
        "i10",
        "i20",
        "i25",
        "i30",
        "i35",
        "Elantra",
        "Sonata",
        "Accent",
        "Getz",
        "Tucson",
        "Santa Fe",
        "Kona",
        "Ioniq",
        "Venue",
        "Palisade",
        "Veloster",
        "ix35",
        "Terracan",
        "Matrix",
        "Trajet",
        "H1",
        "i800",
        "Bayon",
        "Staria",
        "Ioniq 5",
        "Ioniq 6",
        "Atos",
        "Lavita",
        "Veracruz",
        "i40"
    ],
    "Kia": [
        "Picanto",
        "Rio",
        "Ceed",
        "Ceed SW",
        "Pro-Ceed",
        "Forte",
        "Stonic",
        "Sportage",
        "Sorento",
        "Niro",
        "Telluride",
        "Seltos",
        "Xceed",
        "Cerato",
        "Magentis",
        "Optima",
        "Carnival",
        "Venga",
        "Soul",
        "Carens",
        "EV6",
        "EV9",
        "Stinger",
        "Shuma"
    ],
    "Mazda": [
        "Mazda2",
        "Mazda3",
        "Mazda5",
        "Mazda6",
        "CX-3",
        "CX-30",
        "CX-5",
        "CX-50",
        "CX-60",
        "CX-9",
        "MX-5",
        "Tribute",
        "MPV",
        "BT-50",
        "Demio",
        "Lantis",
        "RX-8",
        "MX-30"
    ],
    "Skoda": [
        "Fabia",
        "Octavia",
        "Superb",
        "Rapid",
        "Scala",
        "Kamiq",
        "Karoq",
        "Kodiaq",
        "Enyaq",
        "Yeti",
        "Roomster",
        "Citigo"
    ],
    "Mitsubishi": [
        "Space Star",
        "Colt",
        "Lancer",
        "ASX",
        "Outlander",
        "Eclipse Cross",
        "Pajero",
        "Triton",
        "Grandis",
        "Hunter",
        "i-MiEV",
        "Attrage"
    ],
    "Suzuki": [
        "Alto",
        "Splash",
        "Swift",
        "Baleno",
        "Ignis",
        "Vitara",
        "SX4",
        "Jimny",
        "Grand Vitara",
        "Liana",
        "Kizashi",
        "Celerio",
        "S-Cross"
    ],
    "Nissan": [
        "Micra",
        "Juke",
        "Qashqai",
        "X-Trail",
        "Leaf",
        "Note",
        "Tiida",
        "Almera",
        "Maxima",
        "Murano",
        "Pathfinder",
        "Terrano",
        "Navara",
        "Ariya",
        "Sentra",
        "Armada",
        "Z",
        "Altima",
        "370Z",
        "GTR",
        "NV200",
        "Patrol"
    ],
    "Subaru": [
        "Impreza",
        "Crosstrek",
        "Forester",
        "Outback",
        "Evoltis",
        "XV",
        "B4",
        "B3",
        "Levorg",
        "BRZ",
        "Solterra",
        "Justy"
    ],
    "Honda": [
        "Jazz",
        "Civic",
        "HR-V",
        "CR-V",
        "Accord",
        "FR-V",
        "Insight",
        "ZR-V",
        "e:Ny1",
        "Zest"
    ],
    "Ford": [
        "Fiesta",
        "Focus",
        "Puma",
        "Kuga",
        "Explorer",
        "Mustang",
        "Mustang Mach-E",
        "Mondeo",
        "S-MAX",
        "Galaxy",
        "Ranger",
        "Fusion",
        "Ecosport",
        "Everest",
        "Five Hundred",
        "Econoline"
    ],
    "Chevrolet": [
        "Spark",
        "Cruze",
        "Malibu",
        "Trax",
        "Equinox",
        "Traverse",
        "Savana",
        "Silverado",
        "Aveo",
        "Optra",
        "Sonic",
        "Volt",
        "Orlando",
        "Captiva",
        "Uplander",
        "Vivant"
    ],
    "Volkswagen": [
        "Polo",
        "Golf",
        "T-Roc",
        "T-Cross",
        "Tiguan",
        "Taigo",
        "Passat",
        "Arteon",
        "Touran",
        "Sharan",
        "Touareg",
        "Amarok",
        "Jetta",
        "Beetle",
        "Scirocco",
        "Bora",
        "ID.3",
        "ID.4",
        "ID.5",
        "ID.Buzz"
    ],
    "Peugeot": [
        "108",
        "208",
        "2008",
        "308",
        "3008",
        "5008",
        "508",
        "Rifter",
        "Partner",
        "107",
        "206",
        "207",
        "307",
        "407",
        "301",
        "RCZ",
        "Traveller",
        "e-208",
        "e-2008",
        "4007",
        "408"
    ],
    "Citroen": [
        "C1",
        "C3",
        "C3 Aircross",
        "C4",
        "C4 Sedan",
        "C4 X",
        "C5 Aircross",
        "C5 X",
        "Berlingo",
        "Jumpy",
        "C2",
        "C4 Picasso",
        "Grand C4 Picasso",
        "C-Elysee",
        "DS3",
        "DS4",
        "DS5",
        "Xsara",
        "Xsara Picasso"
    ],
    "Renault": [
        "Clio",
        "Clio B",
        "Megane",
        "Captur",
        "Kadjar",
        "Arkana",
        "Austral",
        "Scenic",
        "Grand Scenic",
        "Fluence",
        "Koleos",
        "Laguna",
        "Talisman",
        "Zoe",
        "Twingo"
    ],
    "Seat": [
        "Ibiza",
        "Leon",
        "Arona",
        "Ateca",
        "Tarraco",
        "Alhambra",
        "Mii",
        "Toledo",
        "Altea",
        "Cordoba"
    ],
    "Opel": [
        "Corsa",
        "Astra",
        "Mokka",
        "Crossland",
        "Grandland",
        "Insignia",
        "Combo",
        "Zafira",
        "Adam",
        "Meriva",
        "GT",
        "Speedster"
    ],
    "Fiat": [
        "500",
        "500X",
        "Tipo",
        "Panda",
        "Punto",
        "Grande Punto",
        "Bravo",
        "Doblo",
        "Qubo",
        "Multipla",
        "500e",
        "Stilo",
        "Croma"
    ],
    "Dacia": [
        "Sandero",
        "Duster",
        "Jogger",
        "Logan",
        "Dokker",
        "Lodgy"
    ],
    "Alfa Romeo": [
        "147",
        "156",
        "159",
        "GT",
        "Brera",
        "Spider",
        "MiTo",
        "Giulietta",
        "Giulia",
        "Stelvio",
        "Tonale"
    ],
    "Lancia": [
        "Ypsilon",
        "Delta",
        "Thesis",
        "Musa"
    ],
    "Volvo": [
        "S60",
        "S90",
        "V60",
        "V90",
        "XC40",
        "XC60",
        "XC90",
        "C40",
        "EX30",
        "EX90",
        "S40",
        "V40",
        "C30",
        "S80"
    ],
    "Audi": [
        "A1",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "Q2",
        "Q3",
        "Q4 e-tron",
        "Q5",
        "Q7",
        "Q8",
        "Q8 e-tron",
        "e-tron GT",
        "TT",
        "R8"
    ],
    "BMW": [
        "Series 1",
        "Series 2",
        "Series 3",
        "Series 4",
        "Series 5",
        "Series 6",
        "Series 7",
        "Series 8",
        "X1",
        "X2",
        "X3",
        "X4",
        "X5",
        "X6",
        "X7",
        "Z4",
        "iX1",
        "iX3",
        "iX",
        "i4",
        "i5",
        "i7"
    ],
    "Mercedes-Benz": [
        "A-Class",
        "B-Class",
        "C-Class",
        "E-Class",
        "S-Class",
        "CLA",
        "CLS",
        "GLA",
        "GLB",
        "GLC",
        "GLE",
        "GLS",
        "EQA",
        "EQB",
        "EQC",
        "EQE",
        "EQS",
        "G-Class",
        "SL",
        "AMG GT",
        "Vito",
        "Citan",
        "Sprinter",
        "V-Class",
        "GLK-Class",
        "M-Class",
        "R-Class"
    ],
    "Lexus": [
        "CT",
        "IS",
        "ES",
        "GS",
        "LS",
        "UX",
        "NX",
        "RX",
        "RZ",
        "GX",
        "LM",
        "GSF",
        "SC430"
    ],
    "Cadillac": [
        "CTS",
        "STS",
        "SRX",
        "ATS",
        "XT4",
        "XT5",
        "XT6",
        "Escalade",
        "Lyriq",
        "BLS"
    ],
    "Infiniti": [
        "Q30",
        "Q50",
        "Q60",
        "Q70",
        "QX30",
        "QX50",
        "QX60",
        "QX70",
        "QX80",
        "FX",
        "G37"
    ],
    "Jaguar": [
        "XE",
        "XF",
        "XJ",
        "F-Pace",
        "E-Pace",
        "I-Pace",
        "F-Type",
        "S-Type",
        "X-Type"
    ],
    "Land Rover": [
        "Defender",
        "Discovery",
        "Discovery Sport",
        "Range Rover",
        "Range Rover Sport",
        "Range Rover Velar",
        "Range Rover Evoque",
        "Freelander"
    ],
    "Porsche": [
        "911",
        "718 Boxster",
        "718 Cayman",
        "Panamera",
        "Taycan",
        "Macan",
        "Cayenne"
    ],
    "Maserati": [
        "Ghibli",
        "Quattroporte",
        "Levante",
        "Grecale",
        "GranTurismo",
        "MC20"
    ],
    "Tesla": [
        "Model 3",
        "Model Y",
        "Model S",
        "Model X"
    ],
    "BYD": [
        "Atto 3",
        "Dolphin",
        "Seal",
        "Tang",
        "Han",
        "Seal U"
    ],
    "MG": [
        "ZS",
        "EHS",
        "Marvel R",
        "MG4",
        "MG5",
        "HS",
        "MG3",
        "Cyberster"
    ],
    "Geely": [
        "Geometry C",
        "Geometry E",
        "Starray"
    ],
    "Chery": [
        "Tiggo 7 Pro",
        "Tiggo 8 Pro",
        "FX (Omoda 5)",
        "Tiggo 5",
        "eQ7",
        "Tiggo 4 Pro",
        "Arrizo 8"
    ],
    "GAC": [
        "GE3",
        "Aion Y"
    ],
    "Aiways": [
        "U5"
    ],
    "Seres": [
        "3",
        "5"
    ],
    "Skywell": [
        "ET5"
    ],
    "Maxus": [
        "Euniq 5",
        "Euniq 6",
        "T90"
    ],
    "Jeep": [
        "Wrangler",
        "Grand Cherokee",
        "Cherokee",
        "Compass",
        "Renegade",
        "Commander",
        "Avenger"
    ],
    "Chrysler": [
        "300C",
        "Grand Voyager",
        "PT Cruiser"
    ],
    "Dodge": [
        "Ram",
        "Caliber",
        "Nitro",
        "Journey"
    ],
    "Daihatsu": [
        "Sirion",
        "Terios",
        "Materia",
        "Charade",
        "YRV",
        "Copen"
    ],
    "Saab": [
        "9-3",
        "9-5"
    ],
    "Rover": [
        "25",
        "45",
        "75"
    ],
    "Abarth": [
        "500",
        "595",
        "124 Spider"
    ]
}